const SECOND = 1000;
const MINUTE = SECOND * 60;
const HOUR = MINUTE * 60;
const DAY = HOUR * 24;
const WEEK = DAY * 7;

// Timely/Claims
const TIME_BETWEEN_TIMELY_CLAIMS = 2 * HOUR;
const TIME_TO_RESET_TIMELY_STREAK = 2 * WEEK;

const TIME_BETWEEN_DAILY_CLAIMS = 23 * HOUR;
const TIME_TO_RESET_DAILY_STREAK = 2 * WEEK;

const PAUSED_TIME_TO_RESET_STREAK = 10 * WEEK;

module.exports = {
  SECOND,
  MINUTE,
  HOUR,
  DAY,
  WEEK,
  TIME_BETWEEN_TIMELY_CLAIMS,
  TIME_TO_RESET_TIMELY_STREAK,
  TIME_BETWEEN_DAILY_CLAIMS,
  TIME_TO_RESET_DAILY_STREAK,
  PAUSED_TIME_TO_RESET_STREAK,
};
