version: "3"
services:
  discord-bot-pokeclicker:
    build: .
    container_name: discord-bot-pokequiz
    command: ["pm2-runtime", "start", "ecosystem.config.js"]
    volumes:
      - ./:/usr/src/bot
      - /usr/src/bot/node_modules/
    working_dir: /usr/src/bot
    restart: unless-stopped
# docker-compose up --force-recreate --build -d
