name = "poke-quiz"
main = "./index.js"
type = "javascript"
compatibility_date="2024-11-25"

account_id = "9a3591e2beedbd153f862cf845103192"
workers_dev = true

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[env.dev]

[env.production]

# [secrets]
# DISCORD_APP_ID
# DISCORD_PUBLIC_KEY
# DISCORD_BOT_TOKEN
# GUILD_ID
# BACKUP_CHANNEL_ID
# QUIZ_CHANNEL_ID